package learning.task042;

import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertNotEquals;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.junit.jupiter.api.Assertions.assertTrue;

class PlayerRepositoryTest {
    private Connection connection;

    @BeforeEach
    void prepareDatabase() throws SQLException {
        connection = DriverManager.getConnection("jdbc:h2:mem:task042_" + System.nanoTime() + ";MODE=PostgreSQL");
        try (Statement statement = connection.createStatement()) {
            statement.execute("CREATE TABLE players (id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, nickname VARCHAR(100) NOT NULL UNIQUE, level INTEGER NOT NULL CHECK (level BETWEEN 1 AND 100))");
            statement.execute("INSERT INTO players (id, nickname, level) VALUES (500, 'Veteran', 50)");
        }
    }

    @AfterEach
    void closeDatabase() throws SQLException {
        if (connection != null && !connection.isClosed()) {
            connection.close();
        }
    }

    @Test
    void savesPlayerAndReturnsDatabaseGeneratedId() throws SQLException {
        Player saved = new PlayerRepository(connection).save("Kira", 42);

        assertTrue(saved.id() > 0);
        assertNotEquals(500, saved.id());
        assertEquals("Kira", saved.nickname());
        assertEquals(42, saved.level());
        try (PreparedStatement statement = connection.prepareStatement(
                "SELECT nickname, level FROM players WHERE id = ?")) {
            statement.setInt(1, saved.id());
            try (ResultSet rows = statement.executeQuery()) {
                assertTrue(rows.next(), "Выданный ID должен указывать на сохранённого игрока");
                assertEquals("Kira", rows.getString("nickname"));
                assertEquals(42, rows.getInt("level"));
                assertFalse(rows.next());
            }
        }
    }

    @Test
    void acceptsBoundaryLevelsAndReturnsDifferentIds() throws SQLException {
        PlayerRepository repository = new PlayerRepository(connection);
        Player first = repository.save("Newcomer", 1);
        Player second = repository.save("Champion", 100);

        assertEquals(1, first.level());
        assertEquals(100, second.level());
        assertNotEquals(first.id(), second.id());
        assertEquals(3, countPlayers());
    }

    @Test
    void preservesNicknameSpaces() throws SQLException {
        Player saved = new PlayerRepository(connection).save(" Kira ", 42);
        assertEquals(" Kira ", saved.nickname());
        try (PreparedStatement statement = connection.prepareStatement("SELECT nickname FROM players WHERE id = ?")) {
            statement.setInt(1, saved.id());
            try (ResultSet rows = statement.executeQuery()) {
                assertTrue(rows.next());
                assertEquals(" Kira ", rows.getString("nickname"));
            }
        }
    }

    @Test
    void rejectsInvalidArgumentsWithoutWritingRows() throws SQLException {
        PlayerRepository repository = new PlayerRepository(connection);
        assertThrows(IllegalArgumentException.class, () -> repository.save(null, 10));
        assertThrows(IllegalArgumentException.class, () -> repository.save("", 10));
        assertThrows(IllegalArgumentException.class, () -> repository.save("   ", 10));
        assertThrows(IllegalArgumentException.class, () -> repository.save("Nova", 0));
        assertThrows(IllegalArgumentException.class, () -> repository.save("Nova", 101));
        assertEquals(1, countPlayers());
    }

    @Test
    void reportsDuplicateNicknameAsSqlError() throws SQLException {
        PlayerRepository repository = new PlayerRepository(connection);
        repository.save("Kira", 42);
        assertThrows(SQLException.class, () -> repository.save("Kira", 43));
        assertEquals(2, countPlayers());
    }

    @Test
    void rejectsNullConnection() {
        assertThrows(IllegalArgumentException.class, () -> new PlayerRepository(null));
    }

    @Test
    void propagatesClosedConnectionError() throws SQLException {
        PlayerRepository repository = new PlayerRepository(connection);
        connection.close();
        assertThrows(SQLException.class, () -> repository.save("Kira", 42));
    }

    @Test
    void keepsCallerConnectionOpen() throws SQLException {
        new PlayerRepository(connection).save("Kira", 42);
        assertFalse(connection.isClosed());
    }

    private int countPlayers() throws SQLException {
        try (Statement statement = connection.createStatement();
             ResultSet rows = statement.executeQuery("SELECT COUNT(*) FROM players")) {
            rows.next();
            return rows.getInt(1);
        }
    }
}
