-- Создай здесь таблицы players и player_orders.
-- Используй ограничения из условия задачи.
CREATE TABLE players (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nickname VARCHAR NOT NULL UNIQUE,
    level INTEGER NOT NULL CHECK ( level > 0 AND level <= 100 )
);

CREATE TABLE player_orders (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    player_id INTEGER NOT NULL,
    item_name VARCHAR NOT NULL,
    total_price DECIMAL(10, 2) NOT NULL CHECK ( total_price >= 0 ),
    purchased_at DATE NOT NULL,
    FOREIGN KEY (player_id) REFERENCES players(id)
);