spring.datasource.url=${COURSE_PG_URL}
spring.datasource.username=${COURSE_PG_USER}
spring.datasource.password=${COURSE_PG_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
